DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS requests
(
    "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app         varchar(50)  NOT NULL,
    "uri"       varchar(255) NOT NULL,
    ip          varchar(50)  NOT NULL,
    "timestamp" timestamp    NOT NULL
);