DROP TABLE IF EXISTS "event_requests" CASCADE;
DROP TABLE IF EXISTS "compilation_events" CASCADE;
DROP TABLE IF EXISTS "compilations" CASCADE;
DROP TABLE IF EXISTS "locations" CASCADE;
DROP TABLE IF EXISTS "events" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;


CREATE TABLE IF NOT EXISTS "users"
(
    "id"    bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" varchar(255) NOT NULL UNIQUE,
    "name"  varchar(255) NOT NULL,
    CONSTRAINT "users_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "compilations"
(
    "id"          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title"        varchar(255) NOT NULL UNIQUE,
    "pinned"      BOOLEAN      NOT NULL DEFAULT 'false',
    CONSTRAINT "compilations_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "compilation_events"
(
    "id"             bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "compilation_id" integer NOT NULL,
    "event_id"       integer NOT NULL,
    CONSTRAINT "compilation_events_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "categories"
(
    "id"   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL UNIQUE,
    CONSTRAINT "categories_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "events"
(
    "id"                 bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "annotation"         varchar(255) NOT NULL,
    "description"        varchar      NOT NULL,
    "event_date"         TIMESTAMP    NOT NULL,
    "paid"               BOOLEAN      NOT NULL DEFAULT 'true',
    "participants_limit" integer      NOT NULL,
    "request_moderation" BOOLEAN      NOT NULL DEFAULT 'true',
    "title"              varchar(255) NOT NULL,
    "category_id"        integer      NOT NULL,
    "created_on"         TIMESTAMP    NOT NULL,
    "published_on"       TIMESTAMP,
    "initiator_id"       integer      NOT NULL,
    "location_id"        integer      NOT NULL,
    "status"             varchar(255) NOT NULL,
    CONSTRAINT "events_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "event_requests"
(
    "id"           bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_id"     integer      NOT NULL,
    "requester_id" integer      NOT NULL,
    "status"       varchar(255) NOT NULL,
    "timestamp"    TIMESTAMP    NOT NULL,
    CONSTRAINT "event_requests_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "locations"
(
    "id"         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "latitude"   float  NOT NULL,
    "longtitude" float  NOT NULL,
    CONSTRAINT "locations_pk" PRIMARY KEY ("id")
);

ALTER TABLE "events"
    ADD CONSTRAINT "events_fk_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE;
ALTER TABLE "events"
    ADD CONSTRAINT "events_fk_initiator_id" FOREIGN KEY ("initiator_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "events"
    ADD CONSTRAINT "events_fk_location_id" FOREIGN KEY ("location_id") REFERENCES "locations" ("id") ON DELETE CASCADE;

ALTER TABLE "event_requests"
    ADD CONSTRAINT "event_requests_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;
ALTER TABLE "event_requests"
    ADD CONSTRAINT "event_requests_fk_users_id" FOREIGN KEY ("requester_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "compilation_events"
    ADD CONSTRAINT "compilation_events_fk_compilations_id" FOREIGN KEY ("compilation_id") REFERENCES "compilations" ("id") ON DELETE CASCADE;
ALTER TABLE "compilation_events"
    ADD CONSTRAINT "compilation_events_fk_events_id" FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON DELETE CASCADE;