DROP TABLE IF EXISTS "event_requests";
DROP TABLE IF EXISTS "event_permissions";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "events";
DROP TABLE IF EXISTS "compilations";
DROP TABLE IF EXISTS "categories";



CREATE TABLE IF NOT EXISTS "users"
(
    "id"    bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" varchar(255) NOT NULL UNIQUE,
    "name"  varchar(255) NOT NULL,
    CONSTRAINT "users_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "compilations"
(
    "id"          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"        varchar(255) NOT NULL,
    "description" varchar      NOT NULL,
    CONSTRAINT "compilations_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "categories"
(
    "id"   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL UNIQUE,
    CONSTRAINT "categories_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "events"
(
    "id"                 bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "annotation"         varchar(255) NOT NULL,
    "description"        varchar      NOT NULL,
    "event_date"         TIMESTAMP    NOT NULL,
    "latitude"           FLOAT        NOT NULL,
    "longitude"          FLOAT        NOT NULL,
    "participants_limit" integer      NOT NULL,
    "request_moderation" BOOLEAN      NOT NULL DEFAULT 'true',
    "title"              varchar(255) NOT NULL,
    "category"           integer      NOT NULL,
    "compilation"        integer              ,
    CONSTRAINT "events_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "event_requests"
(
    "id"        bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event"     integer NOT NULL,
    "requester" integer NOT NULL,
    CONSTRAINT "event_requests_pk" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "event_permissions"
(
    "id"        bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event"     integer      NOT NULL,
    "submitter" integer      NOT NULL,
    "timestamp" TIMESTAMP    NOT NULL,
    "status"    varchar(255) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT "event_permissions_pk" PRIMARY KEY ("id")
);



ALTER TABLE "events"
    ADD CONSTRAINT "events_fk_categories" FOREIGN KEY ("category") REFERENCES "categories" ("id") ON DELETE CASCADE;
ALTER TABLE "events"
    ADD CONSTRAINT "events_fk_compilations" FOREIGN KEY ("compilation") REFERENCES "compilations" ("id") ON DELETE CASCADE;

ALTER TABLE "event_requests"
    ADD CONSTRAINT "event_requests_fk_events_id" FOREIGN KEY ("event") REFERENCES "events" ("id") ON DELETE CASCADE;
ALTER TABLE "event_requests"
    ADD CONSTRAINT "event_requests_fk_users_id" FOREIGN KEY ("requester") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "event_permissions"
    ADD CONSTRAINT "event_permissions_fk_events_id" FOREIGN KEY ("event") REFERENCES "events" ("id") ON DELETE CASCADE;
ALTER TABLE "event_permissions"
    ADD CONSTRAINT "event_permissions_fk_users_id" FOREIGN KEY ("submitter") REFERENCES "users" ("id") ON DELETE CASCADE;